export const vehicleExamples = [
  {
    categoryId: "hatch",
    dailyPrice: 120,
    description: "Hatch Manual",
    id: "hb20",
    imageAlt: "Hyundai HB20 1.0 preto",
    imageSrc: "/assets/hermex/vehicles/hb20.png",
    vehicleName: "Hyundai HB20 1.0",
  },
  {
    categoryId: "hatch",
    dailyPrice: 130,
    description: "Hatch Automático",
    id: "honda-city",
    imageAlt: "Honda City azul",
    imageSrc: "/assets/hermex/vehicles/honda-city.png",
    vehicleName: "Honda City",
  },
  {
    categoryId: "suv",
    dailyPrice: 140,
    description: "SUV Automático",
    id: "renegade",
    imageAlt: "Jeep Renegade 1.3 preto",
    imageSrc: "/assets/hermex/vehicles/renegade.png",
    vehicleName: "Jeep Renegade 1.3",
  },
  {
    categoryId: "sedan",
    dailyPrice: 130,
    description: "Sedan Manual",
    id: "fiat-cronos",
    imageAlt: "Fiat Cronos preto",
    imageSrc: "/assets/hermex/vehicles/fiat-cronos.png",
    vehicleName: "Fiat Cronos",
  },
  {
    categoryId: "hatch",
    dailyPrice: 130,
    description: "Hatch Automático",
    id: "onix",
    imageAlt: "Onix LTZ 1.0 vermelho",
    imageSrc: "/assets/hermex/vehicles/onix.png",
    vehicleName: "Onix LTZ 1.0",
  },
  {
    categoryId: "minivan",
    dailyPrice: 320,
    description: "Minivan Automática 7 Lugares",
    id: "gm-spin",
    imageAlt: "GM Spin 1.8 azul",
    imageSrc: "/assets/hermex/vehicles/gm-spin.png",
    vehicleName: "GM Spin 1.8",
  },
  {
    categoryId: "suv",
    dailyPrice: 150,
    description: "SUV Automático",
    id: "vw-t-cross",
    imageAlt: "VW T-Cross 1.0 Turbo prata",
    imageSrc: "/assets/hermex/vehicles/vw-t-cross.png",
    vehicleName: "VW T-Cross 1.0 Turbo",
  },
  {
    categoryId: "sedan",
    dailyPrice: 150,
    description: "Intermediário Automático",
    id: "honda-city-sedan",
    imageAlt: "Honda City Sedan AT azul",
    imageSrc: "/assets/hermex/vehicles/honda-city-sedan.png",
    vehicleName: "Honda City Sedan AT",
  },
  {
    categoryId: "compacto",
    dailyPrice: 100,
    description: "Compacto com Ar",
    id: "fiat-mobi",
    imageAlt: "Fiat Mobi 1.0 vermelho",
    imageSrc: "/assets/hermex/vehicles/fiat-mobi.png",
    vehicleName: "Fiat Mobi 1.0",
  },
] as const;

export const categoryExamples = [
  { id: "compacto", name: "Compacto" },
  { id: "hatch", name: "Hatch" },
  { id: "sedan", name: "Sedan" },
  { id: "suv", name: "SUV" },
  { id: "minivan", name: "Minivan" },
] as const;
