export const vehicleExamples = [
  {
    dailyPrice: 120,
    description: "Hatch Manual",
    imageAlt: "Hyundai HB20 1.0 preto",
    imageSrc: "/assets/hermex/vehicles/hb20.png",
    vehicleName: "Hyundai HB20 1.0",
  },
  {
    dailyPrice: 130,
    description: "Hatch Automático",
    imageAlt: "Honda City azul",
    imageSrc: "/assets/hermex/vehicles/honda-city.png",
    vehicleName: "Honda City",
  },
  {
    dailyPrice: 140,
    description: "SUV Automático",
    imageAlt: "Jeep Renegade 1.3 preto",
    imageSrc: "/assets/hermex/vehicles/renegade.png",
    vehicleName: "Jeep Renegade 1.3",
  },
  {
    dailyPrice: 130,
    description: "Sedan Manual",
    imageAlt: "Fiat Cronos preto",
    imageSrc: "/assets/hermex/vehicles/fiat-cronos.png",
    vehicleName: "Fiat Cronos",
  },
  {
    dailyPrice: 130,
    description: "Hatch Automático",
    imageAlt: "Onix LTZ 1.0 vermelho",
    imageSrc: "/assets/hermex/vehicles/onix.png",
    vehicleName: "Onix LTZ 1.0",
  },
  {
    dailyPrice: 320,
    description: "Minivan Automática 7 Lugares",
    imageAlt: "GM Spin 1.8 azul",
    imageSrc: "/assets/hermex/vehicles/gm-spin.png",
    vehicleName: "GM Spin 1.8",
  },
  {
    dailyPrice: 150,
    description: "SUV Automático",
    imageAlt: "VW T-Cross 1.0 Turbo prata",
    imageSrc: "/assets/hermex/vehicles/vw-t-cross.png",
    vehicleName: "VW T-Cross 1.0 Turbo",
  },
  {
    dailyPrice: 150,
    description: "Intermediário Automático",
    imageAlt: "Honda City Sedan AT azul",
    imageSrc: "/assets/hermex/vehicles/honda-city-sedan.png",
    vehicleName: "Honda City Sedan AT",
  },
  {
    dailyPrice: 100,
    description: "Compacto com Ar",
    imageAlt: "Fiat Mobi 1.0 vermelho",
    imageSrc: "/assets/hermex/vehicles/fiat-mobi.png",
    vehicleName: "Fiat Mobi 1.0",
  },
] as const;
